global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'login-monitor'
    environment: 'development'

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # 登录监控应用
  - job_name: 'flask-login-app'
    static_configs:
      - targets: ['app:5000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    
  # Prometheus 自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 10s
    
  # Alertmanager 监控
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 10s